// Falco appears at the top of the list because "Captain Falcon" directly
// contains the substring "Falco", causing issues when selecting the former's role

// characters[i] = ["Name in Official Roster", "Name as it appears in the Server roles"]

export const OFFICIAL_NAME_IDX = 0;
export const ROLE_NAME_IDX = 1;

export const characters = [
  ["Falco", "Falco"],
  ["Mario", "Mario"],
  ["Donkey Kong", "DK. Donkey Kong."],
  ["Link", "Link"],
  ["Samus", "Samus"],
  ["Dark Samus", "Samus"],
  ["Yoshi", "Yoshi"],
  ["Kirby", "Kirby"],
  ["Fox", "Fox"],
  ["Pikachu", "Pikachu"],
  ["Luigi", "Luigi"],
  ["Ness", "Ness"],
  ["Captain Falcon", "Captain Falcon"],
  ["Jigglypuff", "Jigglypuff"],
  ["Peach", "Peach"],
  ["Daisy", "Daisy"],
  ["Bowser", "Bowser"],
  ["Ice Climbers", "Ice Climbers"],
  ["Sheik", "Sheik"],
  ["Zelda", "Zelda"],
  ["Dr. Mario", "Mario PhD"],
  ["Pichu", "Pichu"],
  ["Marth", "Marth"],
  ["Lucina", "Lucina"],
  ["Young Link", "Link Bambino"],
  ["Ganondorf", "Ganondorf"],
  ["Mewtwo", "Mewtwo"],
  ["Roy", "Roy"],
  ["Chrom", "Chrom"],
  ["Mr. Game and Watch", "Mr Game&Watch"],
  ["Meta Knight", "Meta Knight"],
  ["Pit", "Pit"],
  ["Dark Pit", "Black Pit"],
  ["Zero Suit Samus", "Zero Suit Samus"],
  ["Wario", "Wario"],
  ["Snake", "Snake"],
  ["Ike", "Ike"],
  ["Squirtle", "Squirtle Trainer"],
  ["Ivysaur", "Ivysaur Trainer"],
  ["Charizard", "Charizard Trainer"],
  ["Diddy Kong", "Diddy Kong"],
  ["Lucas", "Lucas"],
  ["Sonic", "Sonic"],
  ["King Dedede", "DDD"],
  ["Olimar", "Olimar"],
  ["Lucario", "Lucario"],
  ["ROB", "ROB"],
  ["Toon Link", "Tink"],
  ["Wolf", "Wolf"],
  ["Villager", "Villager"],
  ["Mega Man", "Mega Man"],
  ["Wii Fit Trainer", "Wii Fit Trainer"],
  ["Rosalina and Luma", "Rosalina"],
  ["Little Mac", "Little Mac"],
  ["Greninja", "Greninja"],
  ["Mii Brawler", "Mii Brawler"],
  ["Mii Swordfighter", "Mii Swordfighter"],
  ["Mii Gunner", "Mii Gunner"],
  ["Palutena", "Palutena"],
  ["Pac Man", "Pac-Man"],
  ["Robin", "Robin"],
  ["Shulk", "Shulk"],
  ["Bowser Jr", "Bowser Jr"],
  ["Duck Hunt", "Duck Hunt"],
  ["Ryu", "Ryu"],
  ["Ken", "Ken"],
  ["Cloud", "Cloud"],
  ["Corrin", "Corrin"],
  ["Bayonetta", "Bayonetta"],
  ["Inkling", "Squid Kid"],
  ["Ridley", "Ridley"],
  ["Simon", "Simon"],
  ["Richter", "Richard"],
  ["King K Rool", "Krool"],
  ["Isabelle", "Isabelle"],
  ["Incineroar", "Incineroar"],
  ["Piranha Plant", "Piranha Plant"],
  ["Joker", "Joker"],
  ["Hero", "Hero"],
  ["Banjo and Kazooie", "Banjo"],
  ["Terry", "Terry"],
  ["Byleth", "Byleth"],
  ["Min Min", "Min Min"],
  ["Steve", "Steve"],
  ["Sephiroth", "Sephiroth"],
  ["Pyra and Mythra", "Pyra and Mythra"],
  ["Kazuya", "Kazuya"],
  ["Sora", "Sora"],
];
